[2024-06-18T16:43:10.264+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T16:43:10.307+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_create_db_schema scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T16:43:10.316+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_create_db_schema scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T16:43:10.316+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T16:43:10.330+0000] {taskinstance.py:2330} INFO - Executing <Task(SnowflakeOperator): snowflake_create_db_schema> on 2024-06-17 00:00:00+00:00
[2024-06-18T16:43:10.340+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline', 'snowflake_create_db_schema', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/nba_news_stats_etl.py', '--cfg-path', '/tmp/tmp8n14oow5']
[2024-06-18T16:43:10.343+0000] {standard_task_runner.py:91} INFO - Job 105: Subtask snowflake_create_db_schema
[2024-06-18T16:43:10.343+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=8703) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T16:43:10.344+0000] {standard_task_runner.py:63} INFO - Started process 8808 to run task
[2024-06-18T16:43:10.439+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline.snowflake_create_db_schema scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T16:43:10.587+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='snowflake_create_db_schema' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T16:43:10.589+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T16:43:10.601+0000] {sql.py:276} INFO - Executing: 
        CREATE DATABASE IF NOT EXISTS NBA_STATS_ANALYTICS;
        CREATE SCHEMA IF NOT EXISTS NBA_STATS_ANALYTICS.NBA_STATS;
        
[2024-06-18T16:43:10.628+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T16:43:10.651+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T16:43:10.652+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T16:43:10.657+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T16:43:10.657+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 391, in run
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 289, in get_conn
    conn = connector.connect(**conn_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/__init__.py", line 55, in Connect
    return SnowflakeConnection(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/connection.py", line 442, in __init__
    self.connect(**kwargs)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/connection.py", line 707, in connect
    self.__config(**kwargs)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/connection.py", line 1216, in __config
    Error.errorhandler_wrapper(
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 348, in hand_to_other_handler
    connection.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 251001: 251001: Account must be specified
[2024-06-18T16:43:10.681+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_data_pipeline, task_id=snowflake_create_db_schema, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T164310, end_date=20240618T164310
[2024-06-18T16:43:10.693+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 105 for task snowflake_create_db_schema (251001: 251001: Account must be specified; 8808)
[2024-06-18T16:43:10.723+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T16:43:10.751+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class SnowflakeOperator. (This class is deprecated. Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`. Also, you can provide `hook_params={'warehouse': <warehouse>, 'database': <database>, 'role': <role>, 'schema': <schema>, 'authenticator': <authenticator>,'session_parameters': <session_parameters>}`.)
[2024-06-18T16:43:10.765+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T16:43:10.767+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T16:49:49.767+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T16:49:49.814+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_create_db_schema scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T16:49:49.823+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_create_db_schema scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T16:49:49.824+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T16:49:49.838+0000] {taskinstance.py:2330} INFO - Executing <Task(SnowflakeOperator): snowflake_create_db_schema> on 2024-06-17 00:00:00+00:00
[2024-06-18T16:49:49.851+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=12851) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T16:49:49.852+0000] {standard_task_runner.py:63} INFO - Started process 12922 to run task
[2024-06-18T16:49:49.848+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline', 'snowflake_create_db_schema', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/nba_news_stats_etl.py', '--cfg-path', '/tmp/tmpmbgbozzf']
[2024-06-18T16:49:49.853+0000] {standard_task_runner.py:91} INFO - Job 121: Subtask snowflake_create_db_schema
[2024-06-18T16:49:49.949+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline.snowflake_create_db_schema scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T16:49:50.103+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='snowflake_create_db_schema' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T16:49:50.104+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T16:49:50.117+0000] {sql.py:276} INFO - Executing: 
        CREATE DATABASE IF NOT EXISTS NBA_STATS_ANALYTICS;
        CREATE SCHEMA IF NOT EXISTS NBA_STATS_ANALYTICS.NBA_STATS;
        
[2024-06-18T16:49:50.145+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T16:49:50.169+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T16:49:50.170+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T16:49:50.171+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T16:49:50.455+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T16:49:50.455+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 391, in run
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 289, in get_conn
    conn = connector.connect(**conn_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/__init__.py", line 55, in Connect
    return SnowflakeConnection(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/connection.py", line 442, in __init__
    self.connect(**kwargs)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/connection.py", line 745, in connect
    self.__open_connection()
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/connection.py", line 1073, in __open_connection
    self.authenticate_with_retry(self.auth_class)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/connection.py", line 1345, in authenticate_with_retry
    self._authenticate(auth_instance)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/connection.py", line 1373, in _authenticate
    auth.authenticate(
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/auth/_auth.py", line 401, in authenticate
    Error.errorhandler_wrapper(
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 348, in hand_to_other_handler
    connection.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.DatabaseError: 250001 (08001): None: Failed to connect to DB: lv27483.us-east-2.aws.snowflakecomputing.com:443. Incorrect username or password was specified.
[2024-06-18T16:49:50.480+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_data_pipeline, task_id=snowflake_create_db_schema, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T164949, end_date=20240618T164950
[2024-06-18T16:49:50.493+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 121 for task snowflake_create_db_schema (250001 (08001): None: Failed to connect to DB: lv27483.us-east-2.aws.snowflakecomputing.com:443. Incorrect username or password was specified.; 12922)
[2024-06-18T16:49:50.510+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T16:49:50.537+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class SnowflakeOperator. (This class is deprecated. Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`. Also, you can provide `hook_params={'warehouse': <warehouse>, 'database': <database>, 'role': <role>, 'schema': <schema>, 'authenticator': <authenticator>,'session_parameters': <session_parameters>}`.)
[2024-06-18T16:49:50.553+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T16:49:50.555+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T17:38:08.341+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T17:38:08.386+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_create_db_schema scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T17:38:08.395+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_create_db_schema scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T17:38:08.396+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T17:38:08.408+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_create_db_schema> on 2024-06-17 00:00:00+00:00
[2024-06-18T17:38:08.417+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline', 'snowflake_create_db_schema', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/nba_news_stats_etl.py', '--cfg-path', '/tmp/tmp0i69r5sp']
[2024-06-18T17:38:08.420+0000] {standard_task_runner.py:91} INFO - Job 147: Subtask snowflake_create_db_schema
[2024-06-18T17:38:08.420+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3962) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T17:38:08.421+0000] {standard_task_runner.py:63} INFO - Started process 3970 to run task
[2024-06-18T17:38:08.515+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline.snowflake_create_db_schema scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T17:38:08.664+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='snowflake_create_db_schema' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T17:38:08.665+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T17:38:08.680+0000] {sql.py:276} INFO - Executing: 
        CREATE DATABASE IF NOT EXISTS NBA_STATS_ANALYTICS;
        CREATE SCHEMA IF NOT EXISTS NBA_STATS_ANALYTICS.NBA_STATS;
        
[2024-06-18T17:38:08.706+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T17:38:08.950+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T17:38:08.951+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T17:38:08.952+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T17:38:09.284+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T17:38:09.284+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 391, in run
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 289, in get_conn
    conn = connector.connect(**conn_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/__init__.py", line 55, in Connect
    return SnowflakeConnection(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/connection.py", line 442, in __init__
    self.connect(**kwargs)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/connection.py", line 745, in connect
    self.__open_connection()
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/connection.py", line 1073, in __open_connection
    self.authenticate_with_retry(self.auth_class)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/connection.py", line 1345, in authenticate_with_retry
    self._authenticate(auth_instance)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/connection.py", line 1373, in _authenticate
    auth.authenticate(
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/auth/_auth.py", line 401, in authenticate
    Error.errorhandler_wrapper(
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 348, in hand_to_other_handler
    connection.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.DatabaseError: 250001 (08001): None: Failed to connect to DB: lv27483.us-east-2.aws.snowflakecomputing.com:443. Incorrect username or password was specified.
[2024-06-18T17:38:09.309+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_data_pipeline, task_id=snowflake_create_db_schema, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T173808, end_date=20240618T173809
[2024-06-18T17:38:09.321+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 147 for task snowflake_create_db_schema (250001 (08001): None: Failed to connect to DB: lv27483.us-east-2.aws.snowflakecomputing.com:443. Incorrect username or password was specified.; 3970)
[2024-06-18T17:38:09.361+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T17:38:09.401+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T17:38:09.403+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T18:30:29.795+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T18:30:29.888+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_create_db_schema scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T18:30:29.911+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_create_db_schema scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T18:30:29.911+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T18:30:29.943+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_create_db_schema> on 2024-06-17 00:00:00+00:00
[2024-06-18T18:30:29.970+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline', 'snowflake_create_db_schema', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/nba_news_stats_etl.py', '--cfg-path', '/tmp/tmp39_d5dac']
[2024-06-18T18:30:29.985+0000] {standard_task_runner.py:91} INFO - Job 186: Subtask snowflake_create_db_schema
[2024-06-18T18:30:29.984+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=14784) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T18:30:29.994+0000] {standard_task_runner.py:63} INFO - Started process 14885 to run task
[2024-06-18T18:30:30.178+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline.snowflake_create_db_schema scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T18:30:30.498+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='snowflake_create_db_schema' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T18:30:30.506+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T18:30:30.528+0000] {sql.py:276} INFO - Executing: 
        CREATE DATABASE IF NOT EXISTS NBA_STATS_ANALYTICS;
        CREATE SCHEMA IF NOT EXISTS NBA_STATS;
        
[2024-06-18T18:30:30.573+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T18:30:30.925+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T18:30:30.926+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T18:30:30.928+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T18:30:31.627+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T18:30:31.628+0000] {sql.py:487} INFO - Running statement: CREATE DATABASE IF NOT EXISTS NBA_STATS_ANALYTICS;, parameters: None
[2024-06-18T18:30:31.721+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T18:30:31.721+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T18:30:31.721+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T18:30:31.722+0000] {snowflake.py:410} INFO - Snowflake query id: 01b518d6-0001-e49c-0006-023e00017236
[2024-06-18T18:30:31.722+0000] {sql.py:487} INFO - Running statement: CREATE SCHEMA IF NOT EXISTS NBA_STATS;, parameters: None
[2024-06-18T18:30:33.203+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T18:30:33.203+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T18:30:33.203+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T18:30:33.203+0000] {snowflake.py:410} INFO - Snowflake query id: 01b518d6-0001-e498-0006-023e0001b172
[2024-06-18T18:30:33.856+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T18:30:33.857+0000] {connection.py:762} INFO - closed
[2024-06-18T18:30:33.890+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T18:30:33.928+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T18:30:33.982+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=nba_data_pipeline, task_id=snowflake_create_db_schema, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T183029, end_date=20240618T183033
[2024-06-18T18:30:34.036+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T18:30:34.079+0000] {taskinstance.py:3503} INFO - 3 downstream tasks scheduled from follow-on schedule check
[2024-06-18T18:30:34.081+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T18:41:32.062+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T18:41:32.104+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_create_db_schema scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T18:41:32.112+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_create_db_schema scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T18:41:32.113+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T18:41:32.125+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_create_db_schema> on 2024-06-17 00:00:00+00:00
[2024-06-18T18:41:32.134+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=18621) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T18:41:32.136+0000] {standard_task_runner.py:63} INFO - Started process 18629 to run task
[2024-06-18T18:41:32.134+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline', 'snowflake_create_db_schema', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/nba_news_stats_etl.py', '--cfg-path', '/tmp/tmpw_rcrl2l']
[2024-06-18T18:41:32.137+0000] {standard_task_runner.py:91} INFO - Job 208: Subtask snowflake_create_db_schema
[2024-06-18T18:41:32.233+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline.snowflake_create_db_schema scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T18:41:32.384+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='snowflake_create_db_schema' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T18:41:32.385+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T18:41:32.397+0000] {sql.py:276} INFO - Executing: 
        CREATE DATABASE IF NOT EXISTS NBA_STATS_ANALYTICS;
        CREATE SCHEMA IF NOT EXISTS NBA_STATS;
        
[2024-06-18T18:41:32.423+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T18:41:32.665+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T18:41:32.666+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T18:41:32.666+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T18:41:33.071+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T18:41:33.071+0000] {sql.py:487} INFO - Running statement: CREATE DATABASE IF NOT EXISTS NBA_STATS_ANALYTICS;, parameters: None
[2024-06-18T18:41:33.144+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T18:41:33.144+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T18:41:33.145+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T18:41:33.145+0000] {snowflake.py:410} INFO - Snowflake query id: 01b518e1-0001-e497-0006-023e0001d136
[2024-06-18T18:41:33.145+0000] {sql.py:487} INFO - Running statement: CREATE SCHEMA IF NOT EXISTS NBA_STATS;, parameters: None
[2024-06-18T18:41:33.213+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T18:41:33.213+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T18:41:33.213+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T18:41:33.214+0000] {snowflake.py:410} INFO - Snowflake query id: 01b518e1-0001-e495-0006-023e00018192
[2024-06-18T18:41:33.292+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T18:41:33.292+0000] {connection.py:762} INFO - closed
[2024-06-18T18:41:33.324+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T18:41:33.366+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T18:41:33.418+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=nba_data_pipeline, task_id=snowflake_create_db_schema, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T184132, end_date=20240618T184133
[2024-06-18T18:41:33.437+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T18:41:33.480+0000] {taskinstance.py:3503} INFO - 3 downstream tasks scheduled from follow-on schedule check
[2024-06-18T18:41:33.482+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T18:54:25.596+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T18:54:25.638+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_create_db_schema scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T18:54:25.646+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_create_db_schema scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T18:54:25.647+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T18:54:25.659+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_create_db_schema> on 2024-06-17 00:00:00+00:00
[2024-06-18T18:54:25.669+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=22826) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T18:54:25.670+0000] {standard_task_runner.py:63} INFO - Started process 22915 to run task
[2024-06-18T18:54:25.669+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline', 'snowflake_create_db_schema', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '227', '--raw', '--subdir', 'DAGS_FOLDER/nba_news_stats_etl.py', '--cfg-path', '/tmp/tmpg5d6j9pa']
[2024-06-18T18:54:25.671+0000] {standard_task_runner.py:91} INFO - Job 227: Subtask snowflake_create_db_schema
[2024-06-18T18:54:25.764+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline.snowflake_create_db_schema scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T18:54:25.912+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='snowflake_create_db_schema' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T18:54:25.913+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T18:54:25.928+0000] {sql.py:276} INFO - Executing: 
        CREATE DATABASE IF NOT EXISTS NBA_STATS_ANALYTICS;
        CREATE SCHEMA IF NOT EXISTS NBA_STATS;
        
[2024-06-18T18:54:25.954+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T18:54:26.197+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T18:54:26.198+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T18:54:26.198+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T18:54:26.623+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T18:54:26.624+0000] {sql.py:487} INFO - Running statement: CREATE DATABASE IF NOT EXISTS NBA_STATS_ANALYTICS;, parameters: None
[2024-06-18T18:54:26.683+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T18:54:26.684+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T18:54:26.684+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T18:54:26.684+0000] {snowflake.py:410} INFO - Snowflake query id: 01b518ee-0001-e364-0006-023e0001e13e
[2024-06-18T18:54:26.684+0000] {sql.py:487} INFO - Running statement: CREATE SCHEMA IF NOT EXISTS NBA_STATS;, parameters: None
[2024-06-18T18:54:26.753+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T18:54:26.753+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T18:54:26.753+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T18:54:26.754+0000] {snowflake.py:410} INFO - Snowflake query id: 01b518ee-0001-e498-0006-023e0001b1ba
[2024-06-18T18:54:26.825+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T18:54:26.826+0000] {connection.py:762} INFO - closed
[2024-06-18T18:54:26.849+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T18:54:26.882+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T18:54:26.935+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=nba_data_pipeline, task_id=snowflake_create_db_schema, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T185425, end_date=20240618T185426
[2024-06-18T18:54:26.969+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T18:54:27.013+0000] {taskinstance.py:3503} INFO - 3 downstream tasks scheduled from follow-on schedule check
[2024-06-18T18:54:27.016+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T19:09:53.764+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T19:09:53.811+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_create_db_schema scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T19:09:53.820+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_create_db_schema scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T19:09:53.820+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T19:09:53.833+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_create_db_schema> on 2024-06-17 00:00:00+00:00
[2024-06-18T19:09:53.844+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline', 'snowflake_create_db_schema', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/nba_news_stats_etl.py', '--cfg-path', '/tmp/tmpzr9bt4ei']
[2024-06-18T19:09:53.847+0000] {standard_task_runner.py:91} INFO - Job 247: Subtask snowflake_create_db_schema
[2024-06-18T19:09:53.847+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=29212) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T19:09:53.847+0000] {standard_task_runner.py:63} INFO - Started process 29235 to run task
[2024-06-18T19:09:53.952+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline.snowflake_create_db_schema scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T19:09:54.107+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='snowflake_create_db_schema' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T19:09:54.109+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T19:09:54.122+0000] {sql.py:276} INFO - Executing: 
        CREATE DATABASE IF NOT EXISTS NBA_STATS_ANALYTICS;
        CREATE SCHEMA IF NOT EXISTS NBA_STATS;
        
[2024-06-18T19:09:54.148+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T19:09:54.392+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T19:09:54.393+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T19:09:54.394+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T19:09:54.394+0000] {connection.py:1249} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T19:09:54.454+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T19:09:54.702+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T19:09:54.703+0000] {sql.py:487} INFO - Running statement: CREATE DATABASE IF NOT EXISTS NBA_STATS_ANALYTICS;, parameters: None
[2024-06-18T19:09:54.790+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T19:09:54.790+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T19:09:54.791+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T19:09:54.791+0000] {snowflake.py:410} INFO - Snowflake query id: 01b518fd-0001-e499-0006-023e0001c21e
[2024-06-18T19:09:54.791+0000] {sql.py:487} INFO - Running statement: CREATE SCHEMA IF NOT EXISTS NBA_STATS;, parameters: None
[2024-06-18T19:09:54.862+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T19:09:54.862+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T19:09:54.862+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T19:09:54.863+0000] {snowflake.py:410} INFO - Snowflake query id: 01b518fd-0001-e496-0006-023e00019236
[2024-06-18T19:09:54.930+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T19:09:54.930+0000] {connection.py:762} INFO - closed
[2024-06-18T19:09:54.952+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T19:09:54.986+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T19:09:55.040+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=nba_data_pipeline, task_id=snowflake_create_db_schema, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T190953, end_date=20240618T190955
[2024-06-18T19:09:55.071+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T19:09:55.114+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T19:09:55.120+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T20:33:09.569+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T20:33:09.684+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_create_db_schema scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T20:33:09.709+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_create_db_schema scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T20:33:09.710+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T20:33:09.749+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_create_db_schema> on 2024-06-17 00:00:00+00:00
[2024-06-18T20:33:09.787+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline', 'snowflake_create_db_schema', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '274', '--raw', '--subdir', 'DAGS_FOLDER/nba_news_stats_etl.py', '--cfg-path', '/tmp/tmpn2lk1iqh']
[2024-06-18T20:33:09.797+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2134) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T20:33:09.798+0000] {standard_task_runner.py:63} INFO - Started process 2244 to run task
[2024-06-18T20:33:09.795+0000] {standard_task_runner.py:91} INFO - Job 274: Subtask snowflake_create_db_schema
[2024-06-18T20:33:10.065+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline.snowflake_create_db_schema scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T20:33:10.442+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='snowflake_create_db_schema' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T20:33:10.448+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T20:33:10.489+0000] {sql.py:276} INFO - Executing: 
        CREATE DATABASE IF NOT EXISTS NBA_STATS_ANALYTICS;
        CREATE SCHEMA IF NOT EXISTS NBA_STATS;
        
[2024-06-18T20:33:10.556+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T20:33:10.993+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T20:33:10.998+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T20:33:10.999+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T20:33:11.000+0000] {connection.py:1249} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T20:33:11.109+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T20:33:11.643+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T20:33:11.644+0000] {sql.py:487} INFO - Running statement: CREATE DATABASE IF NOT EXISTS NBA_STATS_ANALYTICS;, parameters: None
[2024-06-18T20:33:11.852+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T20:33:11.856+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T20:33:11.857+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T20:33:11.859+0000] {snowflake.py:410} INFO - Snowflake query id: 01b51951-0001-e497-0006-023e0001d222
[2024-06-18T20:33:11.861+0000] {sql.py:487} INFO - Running statement: CREATE SCHEMA IF NOT EXISTS NBA_STATS;, parameters: None
[2024-06-18T20:33:11.991+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T20:33:11.991+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T20:33:11.992+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T20:33:11.992+0000] {snowflake.py:410} INFO - Snowflake query id: 01b51951-0001-e49a-0006-023e0001a2ba
[2024-06-18T20:33:12.073+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T20:33:12.076+0000] {connection.py:762} INFO - closed
[2024-06-18T20:33:12.122+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T20:33:12.204+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T20:33:12.310+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=nba_data_pipeline, task_id=snowflake_create_db_schema, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T203309, end_date=20240618T203312
[2024-06-18T20:33:12.367+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T20:33:12.454+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-18T20:33:12.457+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
