[2024-06-18T16:39:10.364+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: nba_data_pipeline.upload_stats_to_s3 scheduled__2024-06-17T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
